repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.16
    hooks:
      - id: ruff
        args: [--fix]
        stages: [commit, push]
      - id: ruff-format
        stages: [commit, push]
