[changelog]
header = "# Changelog\n\nAll notable changes to arc are documented here.\n\n---\n"
body = """
## [{{ version | trim_start_matches(pat="v") }}] — {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}\
- {{ commit.message | upper_first }}\
{% if commit.id %} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/yash-srivastava19/arc-stack/commit/{{ commit.id }})){% endif %}
{% endfor %}
{% endfor %}
---
"""
trim = true
postprocessors = []

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = []
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^infra|^ci", group = "Infrastructure" },
  { message = "^qol", group = "Added" },
  { message = "^recover", skip = true },
  { message = "^release", skip = true },
  { message = "^chore|^style|^refactor", skip = true },
  { message = "^docs", skip = true },
]
protect_breaking_commits = false
filter_commits = true
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
